### ISSUE TITLE
http-date-0.0.9 fails to build on GHC 7.8 and earlier

### ISSUE THREAD

**Issue by RyanGlScott** [kazu-yamamoto/http-date#12]
`http-date-0.0.9` fails to build on GHC 7.8 or earlier, as shown in [this failing Travis build](https://travis-ci.org/github/scotty-web/wai-middleware-static/jobs/732087586#L747):

```
[4 of 5] Compiling Network.HTTP.Date.Converter ( Network/HTTP/Date/Converter.hs, dist/build/Network/HTTP/Date/Converter.o )

Network/HTTP/Date/Converter.hs:98:48: Not in scope: ‘<$>’

Network/HTTP/Date/Converter.hs:98:74: Not in scope: ‘<*>’
cabal: Failed to build http-date-0.0.9 (which is required by scotty-0.12). See the build log above for details.
```

I can see two possible remedies:

* Restrict the lower version bounds on `base` to `>= 4.8`
* Apply a patch like this:

  ```diff
  diff --git a/Network/HTTP/Date/Converter.hs b/Network/HTTP/Date/Converter.hs
  index 31e0810..4fd98e7 100644
  --- a/Network/HTTP/Date/Converter.hs
  +++ b/Network/HTTP/Date/Converter.hs
  @@ -1,4 +1,5 @@
   {-# LANGUAGE BangPatterns #-}
  +{-# LANGUAGE CPP #-}
   module Network.HTTP.Date.Converter ( epochTimeToHTTPDate
                                      , httpDateToUTC
                                      , utcToHTTPDate
  @@ -14,6 +15,10 @@ import Network.HTTP.Date.Types
   import System.IO.Unsafe (unsafeDupablePerformIO, unsafePerformIO)
   import System.Posix.Types
   
  +#if !(MIN_VERSION_base(4,8,0))
  +import Control.Applicative
  +#endif
  +
   {-|
     Translating 'EpochTime' to 'HTTPDate'.
   -}
  ```
