### PR TITLE
Restrict base to >= 4.8

### LINKED ISSUE #12: http-date-0.0.9 fails to build on GHC 7.8 and earlier
`http-date-0.0.9` fails to build on GHC 7.8 or earlier, as shown in [this failing Travis build](https://travis-ci.org/github/scotty-web/wai-middleware-static/jobs/732087586#L747):

```
[4 of 5] Compiling Network.HTTP.Date.Converter ( Network/HTTP/Date/Converter.hs, dist/build/Network/HTTP/Date/Converter.o )

Network/HTTP/Date/Converter.hs:98:48: Not in scope: ‘<$>’

Network/HTTP/Date/Converter.hs:98:74: Not in scope: ‘<*>’
cabal: Failed to build http-date-0.0.9 (which is required by scotty-0.12). See the build log above for details.
```

I can see two possible remedies:

* Restrict the lower version bounds on `base` to `>= 4.8`
* Apply a patch like this:

  ```diff
  diff --git a/Network/HTTP/Date/Converter.hs b/Network/HTTP/Date/Converter.hs
  index 31e0810..4fd98e7 100644
  --- a/Network/HTTP/Date/Converter.hs
  +++ b/Network/HTTP/Date/Converter.hs
  @@ -1,4 +1,5 @@
   {-# LANGUAGE BangPatterns #-}
  +{-# LANGUAGE CPP #-}
   module Network.HTTP.Date.Converter ( epochTimeToHTTPDate
                                      , httpDateToUTC
                                      , utcToHTTPDate
  @@ -14,6 +15,10 @@ import Network.HTTP.Date.Types
   import System.IO.Unsafe (unsafeDupablePerformIO, unsafePerformIO)
   import System.Posix.Types
   
  +#if !(MIN_VERSION_base(4,8,0))
  +import Control.Applicative
  +#endif
  +
   {-|
     Translating 'EpochTime' to 'HTTPDate'.
   -}
  ```

### PR DESCRIPTION
**Pull request by RyanGlScott**
Fixes #12.

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
Do you want `http-date` for GHC 7.8? Personally, I don't want to maintain my libraries for GHC 7.x anymore.

**Comment by RyanGlScott** [comment]
That's fine. There are two possible solutions listed in #12, and I simply picked one at random :)

I've retooled this PR to instead restrict the lower version bounds on `base` to `>= 4.8` so that this library does not get included in build plans with GHC < 7.10. Can you merge this and apply a corresponding revision to `http-date-0.0.9` on Hackage? Thanks!

**Review by kazu-yamamoto — APPROVED** [review]
LGTM

**Comment by kazu-yamamoto** [comment]
Merged. Thank you for your contribution!

**Comment by RyanGlScott** [comment]
Thanks. But can you also revise the lower version bounds on `base` for `http-date-0.0.9` on Hackage as well? As things currently stand, GHC 7.8 is still broken if you try to install `http-date`:

```
$ cabal install -w /opt/ghc/7.8.4/bin/ghc http-date
Resolving dependencies...
Build profile: -w ghc-7.8.4 -O1
In order, the following will be built (use -v for more details):
 - http-date-0.0.9 (lib) (requires build)
Starting     http-date-0.0.9 (lib)
Building     http-date-0.0.9 (lib)

Failed to build http-date-0.0.9.
Build log (
/home/rgscott/.cabal/logs/ghc-7.8.4/http-date-0.0.9-be01fe65f011f868d31581c8b86b71bbaf523c58f1b95623b7be230a6545199a.log
):
Configuring library for http-date-0.0.9..
Preprocessing library for http-date-0.0.9..
Building library for http-date-0.0.9..
[1 of 5] Compiling Network.HTTP.Date.Types ( Network/HTTP/Date/Types.hs, dist/build/Network/HTTP/Date/Types.o )
[2 of 5] Compiling Network.HTTP.Date.Formatter ( Network/HTTP/Date/Formatter.hs, dist/build/Network/HTTP/Date/Formatter.o )
[3 of 5] Compiling Network.HTTP.Date.Parser ( Network/HTTP/Date/Parser.hs, dist/build/Network/HTTP/Date/Parser.o )
[4 of 5] Compiling Network.HTTP.Date.Converter ( Network/HTTP/Date/Converter.hs, dist/build/Network/HTTP/Date/Converter.o )

Network/HTTP/Date/Converter.hs:98:48: Not in scope: ‘<$>’

Network/HTTP/Date/Converter.hs:98:74: Not in scope: ‘<*>’
cabal: Failed to build http-date-0.0.9. See the build log above for details.
```

**Comment by kazu-yamamoto** [comment]
@RyanGlScott Done. Sorry for your inconvenience.

**Comment by RyanGlScott** [comment]
Thanks again, @kazu-yamamoto!
